### ISSUE TITLE
HOC without the function returns function

### ISSUE THREAD

**Issue by rosskevin** [nordsoftware/react-flow-types#10]
After a day of working on our HOCs, I nailed down all our HOCs to the normal syntax, then bumped into https://github.com/facebook/flow/issues/4644.

We have one HOC that is a direct function, instead of function that returns a function.

Perhaps my brain is fried after a long day, but what is the syntax to remove the outer function from this library's usage?  Here it is based on the example:

```javascript
// ----------------------
// withTheme HOC
type InjectedProps = { theme: Object };
type HOCProps = { option1?: number };

const withTheme = (): HigherOrderComponent<HOCProps, InjectedProps> => (Component: any): any => {
  return (props) => {
    return <Component {...props} />;
  }
}
```

This works with `withTheme()(A)`, but I'm looking for usage like `withTheme(A)`.   Ugh. Any help is appreciated.

**Comment by cniska** [comment]
@AriaMinaei can you help @rosskevin with this?

**Comment by AriaMinaei** [comment]
`const withTheme: HigherOrderComponent<...> = ...` should work :)

**Comment by rosskevin** [comment]
Thanks. Brain fade at the end of a long day. I fixed or HOCs on 100% lint/flow error free code, and suddenly had > 1700 flow errors. All seem valid. Amazing three incorrectly typed HOCs hid so many.
