### ISSUE TITLE
Document gotchas/edge-cases

### ISSUE THREAD

**Issue by AriaMinaei** [nordsoftware/react-flow-types#17]
After the great work by @rsolomon and @rosskevin to get us compatible with 0.57, we seem to have found a few gotchas when dealing with HOCs. These are mentioned in #14 and #16. This issue is a reminder for me and others that these findings should be documented.

**Comment by nik72619c** [comment]
Id like to give it a try

**Comment by AriaMinaei** [comment]
We haven't been working on this project for quite some time. I'd be happy to link to a fork or another well-maintained project.
