### ISSUE TITLE
Usa HigherOrderComponent with HOC returning class component

### ISSUE THREAD

**Issue by michalkvasnicak** [nordsoftware/react-flow-types#4]
`HigherOrderComponent` can't be used with HOC returning React class components?

```js
// returning class component
  (function() {
    const hoc: HigherOrderComponent<{}, { test: boolean }> = () => class extends React.Component {
      render() {
        return (<div test />);
      }
    }
  })();
```

**Comment by michalkvasnicak** [comment]
I didn't notice that I need to type result of hoc as `any`.

**Comment by maartenschumacher** [comment]
@michalkvasnicak are you sure typing the result as `any` is the right solution? doesn't that simply erase the type? i'm asking because looking at the type def for HigherOrderComponent, it only seems to return FunctionalComponent @AriaMinaei

**Comment by cniska** [comment]
@maartenschumacher Aria already gave a thumbs up for his solution so I guess it's OK. @AriaMinaei maybe you can explain this in depth?

**Comment by AriaMinaei** [comment]
Afair, even if your HOC implementation is correct, you still need to cast it to `any` because flow may not be able to infer its type. As long as you're carefully typing the parameters of `HigherOrderComponent<Required, Provided>`, you should be okay.
