### ISSUE TITLE
How to include this module if node_modules are ignored

### ISSUE THREAD

**Issue by klimashkin** [nordsoftware/react-flow-types#8]
I ignore node_modules and I'm trying to include `react-flow-types` into `[libs]` section like explained [here](https://stackoverflow.com/questions/38225538/flow-type-checker-errors-in-node-modules/38264353#38264353) with fbjs.
```
[ignore]
<PROJECT_ROOT>/node_modules/.*

[libs]
<PROJECT_ROOT>/node_modules/react-flow-types
```

But then I anyway got error
```
  5: import type {AnyReactElement} from 'react-flow-types';
                                        ^^^^^^^^^^^^^^^^^^ react-flow-types. Required module not found
```

Is there a way to import types from react-flow-types while ignoring node_modules?

**Comment by AriaMinaei** [comment]
Well, I haven't really needed to ignore the entire `node_modules` folder. I usually only ignore the problematic packages. Although that most likely makes the initial flow pass slower.

But yeah, if you need to ignore the whole `node_modules` folder and whitelist only some of them, you should open an issue in flow's repo :)
